File open feature
CoffeaTeam/fsspec-xrootd pull request #4
Opened 2022-06-17 15:01 UTC by ScottDemarest

This is a redo of the previous pull request. Used flake8, should pass tests this time.

2022-06-17 22:14 UTC, ScottDemarest commented
I fixed most of the typing issues, but there are some I do not know how to resolve. We'll talk about this later

2022-06-21 20:59 UTC, ScottDemarest commented
yay

2022-06-21 23:42 UTC, nsmith- commented
Ok the remaining CI failure seems to be a real issue

2022-06-24 17:03 UTC, nsmith- requested changes

2022-06-24 17:15 UTC, ScottDemarest commented on src/fsspec_xrootd/xrootd.py
> +            self.buffer = io.BytesIO()
Its used in the constructor by default. We dont need it for this branch, but will for the write operations

2022-06-24 17:17 UTC, ScottDemarest commented on tests/File_Read_Feature_Tests.py
> +from __future__ import annotations
my local precommit put that line there. I will remove it for now, but precommit will put it back each time I run it

2022-06-24 17:18 UTC, nsmith- commented on tests/File_Read_Feature_Tests.py
> +from __future__ import annotations
I mean `git rm --cached` the whole file

2022-06-24 17:22 UTC, ScottDemarest commented on tests/File_Read_Feature_Tests.py
> +from __future__ import annotations
Oh, wait, you're right. I'll delete it. Also, do we even need this file? Your test file does everything this one does

2022-06-24 17:23 UTC, ScottDemarest commented on tests/File_Read_Feature_Tests.py
> +from __future__ import annotations
I removed the file

2022-06-24 17:34 UTC, merged